title: duckpond.ch
description: deep inside the pond.. 
author: Ente
github: https://github.com/Enteee
about: I like ducks!
timezone: "Europe/Zurich"
urls:
    - text: About
      url: /about/
    - text: Issues
      url: https://github.com/Enteee/Enteee.github.io/issues
    - text: Atom-feed
      url: /feed.xml
url: "https://duckpond.ch"
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
host: localhost
exclude: ["Gemfile", "Gemfile.lock", "README.md"]
gems:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-sitemap
