title: duckpond.ch
description: deep inside the pond.. 
author: Ente
github: https://github.com/Enteee
about: I like ducks!
timezone: "Etc/GMT+1"
urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml
    - text: Issues
      url: https://github.com/Enteee/Enteee.github.io/issues
url: "https://duckpond.ch"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
    - jekyll-paginate
