title: Duckpond
description: deep inside the pond.. 
author: Ente
github: https://github.com/Enteee
about: I like ducks!
urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml
url: "https://duckpond.ch"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
