version: '2.1'

services:
    jekyll:
        build:
            context: ${CONTAINER_DIR}/jekyll
            args:
                - jekyll_version=${JEKYLL_VERSION}
        command: jekyll build --watch
        volumes:
            - ./:/srv/jekyll:ro
            - www:/srv/jekyll/_site:rw

    jekyll-dev:
        build:
            context: ${CONTAINER_DIR}/jekyll
            args:
                - jekyll_version=${JEKYLL_VERSION}
        command: jekyll build --drafts --watch
        volumes:
            - ./:/srv/jekyll:ro
            - www-dev:/srv/jekyll/_site:rw

    nginx-dockerize:
        image: nginx-dockerize
        build:
            context: ${CONTAINER_DIR}/nginx-dockerize
            args:
                - nginx_version=${NGINX_VERSION}
                - dockerize_version=${DOCKERIZE_VERSION}

    nginx-http:
        depends_on:
            - nginx-dockerize
        image: nginx-http
        build: ${CONTAINER_DIR}/nginx-http
        command: -template ${DOCKERIZE_CONF_DIR}/conf.d/:/etc/nginx/conf.d/ -template ${DOCKERIZE_CONF_DIR}/htpasswd:/etc/nginx/.htpasswd -poll ./start.sh
        volumes:
            - ${CONTAINER_DIR}/nginx-http/conf.d/:${DOCKERIZE_CONF_DIR}/conf.d:ro
            - ${CONTAINER_DIR}/nginx-http/htpasswd:${DOCKERIZE_CONF_DIR}/htpasswd:ro
            - acme-challenge:/usr/share/nginx/letsencrypt/.well-known/acme-challenge:ro
            - www-dev:/usr/share/nginx/html:ro
        networks:
            backbone:
                aliases:
                    - nginx-http

    nginx-https:
        depends_on:
            - nginx-dockerize
            - isso
        build: ${CONTAINER_DIR}/nginx-https
        command: -template ${DOCKERIZE_CONF_DIR}/conf.d/:/etc/nginx/conf.d/ -wait file:///certs/duckpond.ch/cert.pem -wait file:///certs/duckpond.ch/privkey.pem -wait file:///certs/duckpond.ch/fullchain.pem -timeout ${DOCKERIZE_TIMEOUT} ./start.sh
        volumes:
            - ${CONTAINER_DIR}/nginx-https/conf.d/:${DOCKERIZE_CONF_DIR}/conf.d:ro
            - certs:/certs/:ro
            - www:/usr/share/nginx/html:ro
        networks:
            backbone:
                aliases:
                    - duckpond.ch
                    - nginx-https

    letsencrypt:
        depends_on:
            - nginx-http
        build:
            context: ${CONTAINER_DIR}/dehydrated
            args:
                - debian_version=${DEBIAN_VERSION}
        command: dehydrated -c --accept-terms --hook /etc/dehydrated/hook.sh
        volumes:
            - ${CONTAINER_DIR}/dehydrated/etc:/etc/dehydrated:ro
            - certs:/etc/dehydrated/certs:rw
            - ${CONTAINER_DIR}/mailcow/data/assets/ssl:/certs_mailcow:rw
            - acme-challenge:/etc/dehydrated/acme-challenge:rw

    isso:
        build:
            context: ${CONTAINER_DIR}/isso
            args:
                - dockerize_version=${DOCKERIZE_VERSION}
        command: -wait tcp://nginx-https:443 -timeout ${DOCKERIZE_TIMEOUT} /sbin/tini -- run.sh
        environment:
            - GID=${GID}
            - UID=${UID}
        volumes:
            - ${CONTAINER_DIR}/isso/config:/config
            - ${CONTAINER_DIR}/isso/db:/db
        networks:
            backbone:
                aliases:
                    - blog-isso
            mailcow-network:
                aliases:
                    - mailcow-isso

#    openvpn-as:
#        build:
#            context: ${CONTAINER_DIR}/openvpn-as
#            args:
#                - openvpnas_version=${OPENVPNAS_VERSION}
#                - dockerize_version=${DOCKERIZE_VERSION}
#        command: -wait file:///certs/duckpond.ch/cert.pem -wait file:///certs/duckpond.ch/privkey.pem -wait file:///certs/duckpond.ch/fullchain.pem -timeout ${DOCKERIZE_TIMEOUT} /init
#        cap_add:
#            - NET_ADMIN
#        environment:
#            - PUID=1000
#            - PGID=100
#            - TZ=Europe/London
#        volumes:
#            - certs:/certs/:ro
#        ports:
#            - 943:943
#            - 9443:9443
#            - 1194:1194/udp
#        networks:
#            backbone:
#                aliases:
#                    - openvpn
#            mailcow-network:
#                aliases:
#                    - openvpn-mailcow

volumes:
    www:
    www-dev:
    certs:
    acme-challenge:
    openvpn-as:

networks:
    backbone:
    mailcow-network:
