version: '2.1'

services:
    jekyll:
        entrypoint: "/bin/true"

    jekyll-dev:
        volumes:
            - ./:/srv/jekyll:rw

    nginx-dockerize:
        entrypoint: "/bin/true"

    nginx-http:
        ports:
            - 127.0.0.1:80:80
            - 127.0.0.1:8080:8080

    nginx-https:
        entrypoint: "/bin/true"

    letsencrypt:
        entrypoint: "/bin/true"

    isso:
        entrypoint: "/bin/true"

    challenges:

    openvpn-as:
